-- Isolated postseason series pool. The football tables are untouched.
create table if not exists public.pool_baseball_series (
  id bigint generated by default as identity primary key,
  season integer not null default 2026,
  round_key text not null,
  round_name text not null,
  away_team text not null,
  away_mlb_id integer not null,
  away_points integer not null check (away_points between 1 and 20),
  home_team text not null,
  home_mlb_id integer not null,
  home_points integer not null check (home_points between 1 and 20),
  odds_note text,
  lock_at timestamptz not null,
  wins_needed integer not null default 2 check (wins_needed between 2 and 4),
  winner_mlb_id integer,
  winner_at timestamptz,
  flipped_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique(season,round_key,away_mlb_id,home_mlb_id),
  check (away_mlb_id<>home_mlb_id),
  check (winner_mlb_id is null or winner_mlb_id in (away_mlb_id,home_mlb_id))
);
create table if not exists public.pool_baseball_picks (
  series_id bigint not null references public.pool_baseball_series(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  picked_mlb_id integer not null,
  was_anti_clone_flip boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(series_id,user_id)
);
alter table public.pool_baseball_series enable row level security;
alter table public.pool_baseball_picks enable row level security;
revoke all on public.pool_baseball_series,public.pool_baseball_picks from public,anon,authenticated;
grant all on public.pool_baseball_series,public.pool_baseball_picks to service_role;

-- One transaction makes the random flip durable and idempotent before grading.
create or replace function public.settle_baseball_series(p_series_id bigint,p_winner_mlb_id integer default null)
returns void language plpgsql security invoker set search_path = '' as $fn$
declare s public.pool_baseball_series%rowtype; n integer; sides integer; selected integer; chosen uuid;
begin
  select * into s from public.pool_baseball_series where id=p_series_id for update;
  if s.id is null then raise exception 'Series not found'; end if;
  if pg_catalog.now()<s.lock_at then return; end if;
  select count(*),count(distinct picked_mlb_id),min(picked_mlb_id) into n,sides,selected
    from public.pool_baseball_picks where series_id=s.id;
  if n=4 and sides=1 and s.flipped_user_id is null then
    select user_id into chosen from public.pool_baseball_picks where series_id=s.id order by pg_catalog.random() limit 1;
    update public.pool_baseball_picks set picked_mlb_id=case when selected=s.away_mlb_id then s.home_mlb_id else s.away_mlb_id end,
      was_anti_clone_flip=true,updated_at=pg_catalog.now() where series_id=s.id and user_id=chosen;
    update public.pool_baseball_series set flipped_user_id=chosen where id=s.id;
  end if;
  if p_winner_mlb_id is not null and s.winner_mlb_id is null then
    if n<>4 then raise exception 'All four picks are required before grading'; end if;
    if p_winner_mlb_id not in (s.away_mlb_id,s.home_mlb_id) then raise exception 'Invalid series winner'; end if;
    update public.pool_baseball_series set winner_mlb_id=p_winner_mlb_id,winner_at=pg_catalog.now() where id=s.id;
  end if;
end $fn$;
revoke all on function public.settle_baseball_series(bigint,integer) from public,anon,authenticated;
grant execute on function public.settle_baseball_series(bigint,integer) to service_role;

insert into public.pool_baseball_series
(season,round_key,round_name,away_team,away_mlb_id,away_points,home_team,home_mlb_id,home_points,odds_note,lock_at,wins_needed)
values
(2026,'wild_card','Wild Card','Philadelphia Phillies',143,4,'Atlanta Braves',144,4,'ATL -125 / PHI +105','2026-09-29 18:00:00+00',2),
(2026,'wild_card','Wild Card','Chicago White Sox',145,5,'Houston Astros',117,4,'HOU -145 / CWS +125','2026-09-29 21:00:00+00',2),
(2026,'wild_card','Wild Card','Boston Red Sox',111,5,'New York Yankees',147,3,'NYY -170 / BOS +140','2026-09-30 00:00:00+00',2),
(2026,'wild_card','Wild Card','Chicago Cubs',112,4,'San Diego Padres',135,4,'SD -120 / CHC +100','2026-09-30 02:00:00+00',2)
on conflict(season,round_key,away_mlb_id,home_mlb_id) do nothing;

-- Division Series Game 1 begins October 3; pool picks close Friday at 5 p.m. Eastern.
-- Series prices at setup determine the same 3–5 point bands as Wild Card.
insert into public.pool_baseball_series
(season,round_key,round_name,away_team,away_mlb_id,away_points,home_team,home_mlb_id,home_points,odds_note,lock_at,wins_needed)
values
(2026,'division','Division','Chicago White Sox',145,5,'Cleveland Guardians',114,4,'CLE -140 / CWS +120','2026-10-02 21:00:00+00',3),
(2026,'division','Division','Atlanta Braves',144,5,'Los Angeles Dodgers',119,3,'LAD -230 / ATL +190','2026-10-02 21:00:00+00',3),
(2026,'division','Division','New York Yankees',147,4,'Tampa Bay Rays',139,4,'NYY -120 / TB +100','2026-10-02 21:00:00+00',3),
(2026,'division','Division','San Diego Padres',135,5,'Milwaukee Brewers',158,3,'MIL -180 / SD +150','2026-10-02 21:00:00+00',3)
on conflict(season,round_key,away_mlb_id,home_mlb_id) do nothing;
