(()=>{
const ORDER=['Ross','Scott','Jim','Ken'],PRIZES=[18,2,-6,-14];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=x=>(x>0?'+':x<0?'−':'')+'$'+Math.abs(x).toFixed(2);
async function fetchBaseball(){const {data,error}=await sb.functions.invoke('pool-baseball',{body:{}});if(error||data?.error)throw Error(data?.error||error?.message||'Baseball unavailable');return data;}
function totals(data){const points=Object.fromEntries(ORDER.map(n=>[n,0])),payout=Object.fromEntries(ORDER.map(n=>[n,0]));const rounds={};
 for(const s of data.series){const r=rounds[s.round_key]||={series:[],points:Object.fromEntries(ORDER.map(n=>[n,0])),payout:Object.fromEntries(ORDER.map(n=>[n,0]))};r.series.push(s);if(!s.winner_mlb_id)continue;
 for(const p of data.picks.filter(p=>p.series_id===s.id)){if(p.picked_mlb_id!==s.winner_mlb_id||!(p.participant_name in points))continue;const won=s.winner_mlb_id===s.away_mlb_id?s.away_points:s.home_points;points[p.participant_name]+=won;r.points[p.participant_name]+=won}}
 for(const r of Object.values(rounds)){if(!r.series.length||r.series.some(s=>!s.winner_mlb_id))continue;const sorted=ORDER.slice().sort((a,b)=>r.points[b]-r.points[a]);let i=0;while(i<sorted.length){let j=i+1;while(j<sorted.length&&r.points[sorted[j]]===r.points[sorted[i]])j++;const share=PRIZES.slice(i,j).reduce((a,b)=>a+b,0)/(j-i);for(let k=i;k<j;k++){payout[sorted[k]]+=share;r.payout[sorted[k]]+=share}i=j}}
 return {points,payout,rounds};}
window.loadBaseballTotals=async()=>totals(await fetchBaseball());
function ensure(){const nav=document.querySelector('#app nav'),app=document.getElementById('app');if(!nav||!app)return;if(!document.getElementById('baseballBtn')){const b=document.createElement('button');b.id='baseballBtn';b.type='button';b.textContent='Baseball';b.onclick=()=>{show('baseball');loadBaseball()};nav.insertBefore(b,nav.children[1]||null)}if(!document.getElementById('baseball')){const x=document.createElement('section');x.id='baseball';x.className='tab';x.innerHTML='<div class="card"><h2>Postseason Baseball</h2><p id="baseball-status" class="muted">Loading series…</p><div id="baseball-rounds"></div></div>';app.appendChild(x)}if(!document.getElementById('baseball-style')){const s=document.createElement('style');s.id='baseball-style';s.textContent='#baseball .bb-series{border:1px solid #dce3ee;border-radius:12px;padding:15px;margin:13px 0;background:#f7f9fc}#baseball .bb-head{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}#baseball .bb-picks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:10px}#baseball .bb-pick{background:white;border-radius:8px;padding:8px}#baseball select{font:inherit;max-width:100%;padding:5px}#baseball .bb-totals{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:12px 0}#baseball .bb-totals div{padding:10px;background:#eef4ff;border-radius:8px}@media(max-width:440px){#baseball .bb-picks{grid-template-columns:1fr}}';document.head.appendChild(s)}}
function render(data){const box=document.getElementById('baseball-rounds'),status=document.getElementById('baseball-status');if(!box||!status)return;const t=totals(data),groups=Object.entries(t.rounds);status.textContent=data.feedError?'Series results will refresh when MLB is available.':'Series results refresh when you open this tab.';const finished=groups.filter(([,round])=>round.series.every(s=>s.winner_mlb_id));
const history=finished.length?'<section class="bb-history"><h3>Playoff History</h3>'+finished.map(([,round])=>'<div class="bb-series"><h4>'+esc(round.series[0].round_name)+' Series · Final</h4><div class="bb-totals">'+ORDER.map(n=>'<div><b>'+n+'</b>: '+round.points[n]+' pts · '+money(round.payout[n])+'</div>').join('')+'</div>'+round.series.map(s=>{const winner=s.winner_mlb_id===s.away_mlb_id?s.away_team:s.home_team,earned=s.winner_mlb_id===s.away_mlb_id?s.away_points:s.home_points;return '<div class="bb-series"><strong>'+esc(s.away_team)+' @ '+esc(s.home_team)+'</strong><p>Series winner: <b>'+esc(winner)+'</b></p><div class="bb-picks">'+ORDER.map(n=>{const p=data.picks.find(p=>p.series_id===s.id&&p.participant_name===n),picked=p?.picked_mlb_id===s.away_mlb_id?s.away_team:p?.picked_mlb_id===s.home_mlb_id?s.home_team:'No pick';return '<div class="bb-pick"><b>'+n+'</b>: '+esc(picked)+(p?.was_anti_clone_flip?' (random flip)':'')+' · '+(p?.picked_mlb_id===s.winner_mlb_id?earned:0)+' pts</div>'}).join('')+'</div></div>'}).join('')+'</div>').join('')+'</section>':'';
box.innerHTML=groups.filter(([,round])=>!round.series.every(s=>s.winner_mlb_id)).map(([key,round])=>{const complete=round.series.every(s=>s.winner_mlb_id),title=round.series[0].round_name;return '<h3>'+esc(title)+' Series</h3><p class="muted">Pick the series winner. Points shown beside each team. '+(complete?'Round final · $24 awarded.':'$24 awarded after all series end.')+'</p><div class="bb-totals">'+ORDER.map(n=>'<div><b>'+n+'</b>: '+round.points[n]+' pts'+(complete?' · '+money(t.payout[n]):'')+'</div>').join('')+'</div>'+round.series.map(s=>{const locked=Date.now()>=new Date(s.lock_at).getTime(),winner=s.winner_mlb_id,choices=data.picks.filter(p=>p.series_id===s.id);return '<div class="bb-series"><div class="bb-head"><strong>'+esc(s.away_team)+' @ '+esc(s.home_team)+'</strong><span>'+esc(winner?(winner===s.away_mlb_id?s.away_team:s.home_team)+' wins':locked?'Picks locked':'Picks open')+'</span></div><p>'+esc(s.away_team)+' '+s.away_points+' pts · '+esc(s.home_team)+' '+s.home_points+' pts</p><p class="muted">Series odds at setup: '+esc(s.odds_note)+' · Locks '+new Date(s.lock_at).toLocaleString('en-US',{timeZone:'America/New_York',weekday:'short',hour:'numeric',minute:'2-digit',timeZoneName:'short'})+'</p><div class="bb-picks">'+ORDER.map(n=>{const p=choices.find(p=>p.participant_name===n),team=p?.picked_mlb_id===s.away_mlb_id?s.away_team:p?.picked_mlb_id===s.home_mlb_id?s.home_team:'No pick',possible=p?.picked_mlb_id===s.away_mlb_id?s.away_points:p?.picked_mlb_id===s.home_mlb_id?s.home_points:null;return '<div class="bb-pick"><b>'+n+'</b>: '+(data.admin&&!locked?'<select data-series="'+s.id+'" data-name="'+n+'"><option value="">No pick</option><option value="'+s.away_mlb_id+'" '+(p?.picked_mlb_id===s.away_mlb_id?'selected':'')+'>'+esc(s.away_team)+'</option><option value="'+s.home_mlb_id+'" '+(p?.picked_mlb_id===s.home_mlb_id?'selected':'')+'>'+esc(s.home_team)+'</option></select>':esc(team)+(possible==null?'':' ('+possible+' pts)'))+(p?.was_anti_clone_flip?' (random flip)':'')+'</div>'}).join('')+'</div></div>'}).join('')}).join('')+history;box.querySelectorAll('select[data-series]').forEach(select=>select.addEventListener('change',async()=>{if(!select.value)return;select.disabled=true;status.textContent='Saving pick…';const {data:res,error}=await sb.functions.invoke('pool-baseball',{body:{action:'save_pick',series_id:Number(select.dataset.series),participant_name:select.dataset.name,picked_mlb_id:Number(select.value)}});if(error||res?.error){status.textContent=res?.error||error?.message||'Could not save pick';select.disabled=false;return}render(res)}));}
async function loadBaseball(){ensure();try{render(await fetchBaseball())}catch(e){const x=document.getElementById('baseball-status');if(x)x.textContent=e.message||'Baseball unavailable'}}
window.loadBaseball=loadBaseball;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();
