(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const WEEK1={Ken:{wins:10,losses:6,pushes:0,points:10,money:24},Ross:{wins:9,losses:7,pushes:0,points:9,money:-4},Scott:{wins:8,losses:8,pushes:0,points:8,money:-10},Jim:{wins:8,losses:8,pushes:0,points:8,money:-10}};
  const ORDER=['Ross','Scott','Jim','Ken'];
  const WEEK2_MONEY={Ross:24,Scott:-6,Jim:-6,Ken:-12};
  const money=n=>`${n>=0?'+
  const pickFor=(data,gameId,name)=>data.picks.find(p=>p.game_id===gameId&&p.participant_name===name)?.picked_team||'—';
  const pickMark=(g,pick)=>{if(!g.completed||!g.ats_winner||g.ats_winner==='Push'||pick==='—')return'';return pick===g.ats_winner?' ✓':' ✕';};
  const spreadNumber=g=>{const n=Number.parseFloat(String(g.spread??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?Math.abs(n):null;};
  const atsMargin=(g,pick)=>{
    if(pick==='—'||(g.status!=='in'&&!g.completed)||g.away_score===null||g.home_score===null)return null;
    const pts=spreadNumber(g);if(pts===null)return null;
    let pickedScore,otherScore;
    if(pick===g.away_team){pickedScore=Number(g.away_score);otherScore=Number(g.home_score);}
    else if(pick===g.home_team){pickedScore=Number(g.home_score);otherScore=Number(g.away_score);}
    else return null;
    if(!Number.isFinite(pickedScore)||!Number.isFinite(otherScore))return null;
    const raw=pickedScore-otherScore;
    return pick===g.favorite_team?raw-pts:raw+pts;
  };
  const fmtMargin=n=>{if(n===null)return'';if(Math.abs(n)<0.0001)return' (Even)';const v=Math.round(n*10)/10;return ` (${v>0?'+':''}${v})`;};
  const pickClass=n=>n===null?'':Math.abs(n)<0.0001?'pick-push':n>0?'pick-cover':'pick-behind';
  const record=s=>`${s.wins}-${s.losses}${s.pushes?'-'+s.pushes+' P':''}`;
  const rankRows=rows=>[...rows].sort((a,b)=>(b.points-a.points)||(b.wins-a.wins)||(a.losses-b.losses)||a.name.localeCompare(b.name));
  const cards=rows=>'<div class="stand-grid">'+ORDER.map(name=>rows.find(s=>s.name===name)).filter(Boolean).map((s,i)=>`<div><b>${i+1}. ${esc(s.name)}</b><br>${record(s)}<br><span class="muted">${s.points} pts</span><br><b class="${(s.money??0)>0?'money-positive':(s.money??0)<0?'money-negative':''}">${money(s.money??0)}</b></div>`).join('')+'</div>';
  function seasonRows(data){return data.standings.map(s=>{const b=WEEK1[s.name]||{wins:0,losses:0,pushes:0,points:0};return{name:s.name,wins:b.wins+s.wins,losses:b.losses+s.losses,pushes:b.pushes+(s.pushes||0),points:b.points+s.points,money:(b.money||0)+(WEEK2_MONEY[s.name]||0),missing:s.missing};});}
  function ensureUI(){
    if(document.getElementById('live-week'))return;
    const nav=document.querySelector('#app nav');if(!nav)return;
    const adminBtn=document.getElementById('adminBtn'),btn=document.createElement('button');btn.id='liveWeekBtn';btn.textContent='Week 3 Live';btn.type='button';btn.onclick=()=>{show('live-week');loadLiveWeek();};const week3=[...nav.querySelectorAll('button')].find(b=>b.textContent.trim()==='Week 3'); if(week3) nav.insertBefore(btn,week3.nextSibling); else nav.insertBefore(btn,adminBtn||null);
    const section=document.createElement('section');section.id='live-week';section.className='tab';section.innerHTML=`<div class="card"><h2>Week 3 Live</h2><p id="live-week-status" class="muted">Loading published picks and scores…</p><div id="live-week-standings"></div><div id="live-week-games"></div></div>`;document.getElementById('app').appendChild(section);
    const style=document.createElement('style');style.textContent=`#live-week .scoreline{font-size:1.05rem;font-weight:800;margin:5px 0}#live-week .live-badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef4ff;font-size:.8rem;font-weight:800}#live-week .game-live{border-left:5px solid #1769d2}#live-week .game-final{border-left:5px solid #2d7a46}#live-week .game-pre{border-left:5px solid #aebbd0}#live-week .picks-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:10px}#live-week .picks-grid div{background:#f7f9fc;border-radius:8px;padding:7px}#live-week .pick-cover{color:#16833b;font-weight:800}#live-week .pick-behind{color:#c62828;font-weight:800}#live-week .pick-push{color:#111;font-weight:800}.stand-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:8px;margin:12px 0 20px}.stand-grid div{background:#f7f9fc;border:1px solid #e1e7f0;border-radius:10px;padding:10px;text-align:center}.money-positive{color:#2d8a43}.money-negative{color:#b73528}.season-divider{border:0;border-top:1px solid #dfe6ef;margin:22px 0}@media(max-width:650px){.stand-grid{grid-template-columns:repeat(2,1fr)}#live-week .picks-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  }
  function renderStandingsPage(data){const section=document.getElementById('standings');if(!section)return false;const w2=data.standings.map(s=>({...s,money:WEEK2_MONEY[s.name]||0}));section.innerHTML=`<div class="card"><h2>Standings</h2><h3>Week 2 final standings</h3><p class="muted">Final Week 2 record, points and money.</p>${cards(w2)}<hr class="season-divider"><h3>Season total</h3><p class="muted">Week 1 and Week 2 combined.</p>${cards(seasonRows(data))}</div>`;return true;}
  function render(data){const status=document.getElementById('live-week-status');if(status)status.textContent='Published Week '+data.week.week_number+' picks · scores refresh automatically about every minute.';const ls=document.getElementById('live-week-standings');if(ls)ls.innerHTML='<h3>Week '+esc(data.week.week_number)+' standings so far</h3>'+cards(data.standings);renderStandingsPage(data);const lg=document.getElementById('live-week-games');if(!lg)return;lg.innerHTML=[['college','COLLEGE FOOTBALL'],['nfl','NFL']].map(([sport,label])=>`<h3>${label}</h3>`+data.games.filter(g=>g.sport===sport).map(g=>{const cls=g.completed?'game-final':g.status==='in'?'game-live':'game-pre',score=(g.away_score!==null&&g.home_score!==null)?`${esc(g.away_team)} ${g.away_score} · ${esc(g.home_team)} ${g.home_score}`:`${esc(g.away_team)} @ ${esc(g.home_team)}`,ats=g.completed&&g.ats_winner?`ATS: ${esc(g.ats_winner==='Push'?'Push':g.ats_winner+' covered')}`:(g.status==='in'&&g.ats_winner?`Current cover: ${esc(g.ats_winner)}`:'');return `<div class="card ${cls}"><div><span class="live-badge">${esc(g.status_detail||(g.completed?'Final':'Scheduled'))}</span></div><div class="scoreline">${score}</div><div class="muted">Line: ${esc(g.favorite_team)} ${esc(g.spread)}${ats?' · '+ats:''}</div><div class="picks-grid">${data.participants.map(name=>{const p=pickFor(data,g.id,name),m=atsMargin(g,p),pc=pickClass(m);return `<div><b>${esc(name)}</b>: <span class="${pc}">${esc(p)}${fmtMargin(m)}${pickMark(g,p)}</span></div>`;}).join('')}</div></div>`;}).join('')).join('');}
  async function loadLiveWeek(){ensureUI();const status=document.getElementById('live-week-status');try{if(status)status.textContent='Refreshing Week 3…';const {data,error}=await sb.functions.invoke('pool-live',{body:{week_number:3}});if(error)throw error;if(data?.error)throw new Error(data.error);render(data);}catch(e){if(status)status.textContent='Unable to load Week 3 live view: '+(e?.message||'unknown error');}}
  window.loadLiveWeek=loadLiveWeek;
  function start(){ensureUI();document.addEventListener('click',e=>{const b=e.target.closest?.('#app nav button');if(b&&b.textContent.trim()==='Standings')setTimeout(loadLiveWeek,150);},true);setTimeout(loadLiveWeek,800);setInterval(()=>{const live=document.getElementById('live-week')?.classList.contains('show'),stand=document.getElementById('standings')?.classList.contains('show');if(live||stand)loadLiveWeek();},60000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();:'−
  const pickFor=(data,gameId,name)=>data.picks.find(p=>p.game_id===gameId&&p.participant_name===name)?.picked_team||'—';
  const pickMark=(g,pick)=>{if(!g.completed||!g.ats_winner||g.ats_winner==='Push'||pick==='—')return'';return pick===g.ats_winner?' ✓':' ✕';};
  const spreadNumber=g=>{const n=Number.parseFloat(String(g.spread??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?Math.abs(n):null;};
  const atsMargin=(g,pick)=>{
    if(pick==='—'||(g.status!=='in'&&!g.completed)||g.away_score===null||g.home_score===null)return null;
    const pts=spreadNumber(g);if(pts===null)return null;
    let pickedScore,otherScore;
    if(pick===g.away_team){pickedScore=Number(g.away_score);otherScore=Number(g.home_score);}
    else if(pick===g.home_team){pickedScore=Number(g.home_score);otherScore=Number(g.away_score);}
    else return null;
    if(!Number.isFinite(pickedScore)||!Number.isFinite(otherScore))return null;
    const raw=pickedScore-otherScore;
    return pick===g.favorite_team?raw-pts:raw+pts;
  };
  const fmtMargin=n=>{if(n===null)return'';if(Math.abs(n)<0.0001)return' (Even)';const v=Math.round(n*10)/10;return ` (${v>0?'+':''}${v})`;};
  const pickClass=n=>n===null?'':Math.abs(n)<0.0001?'pick-push':n>0?'pick-cover':'pick-behind';
  const record=s=>`${s.wins}-${s.losses}${s.pushes?'-'+s.pushes+' P':''}`;
  const rankRows=rows=>[...rows].sort((a,b)=>(b.points-a.points)||(b.wins-a.wins)||(a.losses-b.losses)||a.name.localeCompare(b.name));
  const cards=rows=>'<div class="stand-grid">'+ORDER.map(name=>rows.find(s=>s.name===name)).filter(Boolean).map((s,i)=>`<div><b>${i+1}. ${esc(s.name)}</b><br>${record(s)}<br><span class="muted">${s.points} pts</span><br><b>${money(s.money??0)}</b></div>`).join('')+'</div>';
  function seasonRows(data){return data.standings.map(s=>{const b=WEEK1[s.name]||{wins:0,losses:0,pushes:0,points:0};return{name:s.name,wins:b.wins+s.wins,losses:b.losses+s.losses,pushes:b.pushes+(s.pushes||0),points:b.points+s.points,money:(b.money||0)+(WEEK2_MONEY[s.name]||0),missing:s.missing};});}
  function ensureUI(){
    if(document.getElementById('live-week'))return;
    const nav=document.querySelector('#app nav');if(!nav)return;
    const adminBtn=document.getElementById('adminBtn'),btn=document.createElement('button');btn.id='liveWeekBtn';btn.textContent='Week 3 Live';btn.type='button';btn.onclick=()=>{show('live-week');loadLiveWeek();};nav.insertBefore(btn,adminBtn||null);
    const section=document.createElement('section');section.id='live-week';section.className='tab';section.innerHTML=`<div class="card"><h2>Week 3 Live</h2><p id="live-week-status" class="muted">Loading published picks and scores…</p><div id="live-week-standings"></div><div id="live-week-games"></div></div>`;document.getElementById('app').appendChild(section);
    const style=document.createElement('style');style.textContent=`#live-week .scoreline{font-size:1.05rem;font-weight:800;margin:5px 0}#live-week .live-badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef4ff;font-size:.8rem;font-weight:800}#live-week .game-live{border-left:5px solid #1769d2}#live-week .game-final{border-left:5px solid #2d7a46}#live-week .game-pre{border-left:5px solid #aebbd0}#live-week .picks-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:10px}#live-week .picks-grid div{background:#f7f9fc;border-radius:8px;padding:7px}#live-week .pick-cover{color:#16833b;font-weight:800}#live-week .pick-behind{color:#c62828;font-weight:800}#live-week .pick-push{color:#111;font-weight:800}.stand-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:8px;margin:12px 0 20px}.stand-grid div{background:#f7f9fc;border:1px solid #e1e7f0;border-radius:10px;padding:10px;text-align:center}.season-divider{border:0;border-top:1px solid #dfe6ef;margin:22px 0}@media(max-width:650px){.stand-grid{grid-template-columns:repeat(2,1fr)}#live-week .picks-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  }
  function renderStandingsPage(data){const section=document.getElementById('standings');if(!section)return false;const w2=data.standings.map(s=>({...s,money:WEEK2_MONEY[s.name]||0}));section.innerHTML=`<div class="card"><h2>Standings</h2><h3>Week 2 final standings</h3><p class="muted">Final Week 2 record, points and money.</p>${cards(w2)}<hr class="season-divider"><h3>Season total</h3><p class="muted">Week 1 and Week 2 combined.</p>${cards(seasonRows(data))}</div>`;return true;}
  function render(data){const status=document.getElementById('live-week-status');if(status)status.textContent='Published Week '+data.week.week_number+' picks · scores refresh automatically about every minute.';const ls=document.getElementById('live-week-standings');if(ls)ls.innerHTML='<h3>Week '+esc(data.week.week_number)+' standings so far</h3>'+cards(data.standings);renderStandingsPage(data);const lg=document.getElementById('live-week-games');if(!lg)return;lg.innerHTML=[['college','COLLEGE FOOTBALL'],['nfl','NFL']].map(([sport,label])=>`<h3>${label}</h3>`+data.games.filter(g=>g.sport===sport).map(g=>{const cls=g.completed?'game-final':g.status==='in'?'game-live':'game-pre',score=(g.away_score!==null&&g.home_score!==null)?`${esc(g.away_team)} ${g.away_score} · ${esc(g.home_team)} ${g.home_score}`:`${esc(g.away_team)} @ ${esc(g.home_team)}`,ats=g.completed&&g.ats_winner?`ATS: ${esc(g.ats_winner==='Push'?'Push':g.ats_winner+' covered')}`:(g.status==='in'&&g.ats_winner?`Current cover: ${esc(g.ats_winner)}`:'');return `<div class="card ${cls}"><div><span class="live-badge">${esc(g.status_detail||(g.completed?'Final':'Scheduled'))}</span></div><div class="scoreline">${score}</div><div class="muted">Line: ${esc(g.favorite_team)} ${esc(g.spread)}${ats?' · '+ats:''}</div><div class="picks-grid">${data.participants.map(name=>{const p=pickFor(data,g.id,name),m=atsMargin(g,p),pc=pickClass(m);return `<div><b>${esc(name)}</b>: <span class="${pc}">${esc(p)}${fmtMargin(m)}${pickMark(g,p)}</span></div>`;}).join('')}</div></div>`;}).join('')).join('');}
  async function loadLiveWeek(){ensureUI();const status=document.getElementById('live-week-status');try{if(status)status.textContent='Refreshing Week 3…';const {data,error}=await sb.functions.invoke('pool-live',{body:{week_number:2}});if(error)throw error;if(data?.error)throw new Error(data.error);render(data);}catch(e){if(status)status.textContent='Unable to load Week 3 live view: '+(e?.message||'unknown error');}}
  window.loadLiveWeek=loadLiveWeek;
  function start(){ensureUI();document.addEventListener('click',e=>{const b=e.target.closest?.('#app nav button');if(b&&b.textContent.trim()==='Standings')setTimeout(loadLiveWeek,150);},true);setTimeout(loadLiveWeek,800);setInterval(()=>{const live=document.getElementById('live-week')?.classList.contains('show'),stand=document.getElementById('standings')?.classList.contains('show');if(live||stand)loadLiveWeek();},60000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();}${Math.abs(n)}`;
  const pickFor=(data,gameId,name)=>data.picks.find(p=>p.game_id===gameId&&p.participant_name===name)?.picked_team||'—';
  const pickMark=(g,pick)=>{if(!g.completed||!g.ats_winner||g.ats_winner==='Push'||pick==='—')return'';return pick===g.ats_winner?' ✓':' ✕';};
  const spreadNumber=g=>{const n=Number.parseFloat(String(g.spread??'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?Math.abs(n):null;};
  const atsMargin=(g,pick)=>{
    if(pick==='—'||(g.status!=='in'&&!g.completed)||g.away_score===null||g.home_score===null)return null;
    const pts=spreadNumber(g);if(pts===null)return null;
    let pickedScore,otherScore;
    if(pick===g.away_team){pickedScore=Number(g.away_score);otherScore=Number(g.home_score);}
    else if(pick===g.home_team){pickedScore=Number(g.home_score);otherScore=Number(g.away_score);}
    else return null;
    if(!Number.isFinite(pickedScore)||!Number.isFinite(otherScore))return null;
    const raw=pickedScore-otherScore;
    return pick===g.favorite_team?raw-pts:raw+pts;
  };
  const fmtMargin=n=>{if(n===null)return'';if(Math.abs(n)<0.0001)return' (Even)';const v=Math.round(n*10)/10;return ` (${v>0?'+':''}${v})`;};
  const pickClass=n=>n===null?'':Math.abs(n)<0.0001?'pick-push':n>0?'pick-cover':'pick-behind';
  const record=s=>`${s.wins}-${s.losses}${s.pushes?'-'+s.pushes+' P':''}`;
  const rankRows=rows=>[...rows].sort((a,b)=>(b.points-a.points)||(b.wins-a.wins)||(a.losses-b.losses)||a.name.localeCompare(b.name));
  const cards=rows=>'<div class="stand-grid">'+ORDER.map(name=>rows.find(s=>s.name===name)).filter(Boolean).map((s,i)=>`<div><b>${i+1}. ${esc(s.name)}</b><br>${record(s)}<br><span class="muted">${s.points} pts</span><br><b>${money(s.money??0)}</b></div>`).join('')+'</div>';
  function seasonRows(data){return data.standings.map(s=>{const b=WEEK1[s.name]||{wins:0,losses:0,pushes:0,points:0};return{name:s.name,wins:b.wins+s.wins,losses:b.losses+s.losses,pushes:b.pushes+(s.pushes||0),points:b.points+s.points,money:(b.money||0)+(WEEK2_MONEY[s.name]||0),missing:s.missing};});}
  function ensureUI(){
    if(document.getElementById('live-week'))return;
    const nav=document.querySelector('#app nav');if(!nav)return;
    const adminBtn=document.getElementById('adminBtn'),btn=document.createElement('button');btn.id='liveWeekBtn';btn.textContent='Week 3 Live';btn.type='button';btn.onclick=()=>{show('live-week');loadLiveWeek();};nav.insertBefore(btn,adminBtn||null);
    const section=document.createElement('section');section.id='live-week';section.className='tab';section.innerHTML=`<div class="card"><h2>Week 3 Live</h2><p id="live-week-status" class="muted">Loading published picks and scores…</p><div id="live-week-standings"></div><div id="live-week-games"></div></div>`;document.getElementById('app').appendChild(section);
    const style=document.createElement('style');style.textContent=`#live-week .scoreline{font-size:1.05rem;font-weight:800;margin:5px 0}#live-week .live-badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef4ff;font-size:.8rem;font-weight:800}#live-week .game-live{border-left:5px solid #1769d2}#live-week .game-final{border-left:5px solid #2d7a46}#live-week .game-pre{border-left:5px solid #aebbd0}#live-week .picks-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:10px}#live-week .picks-grid div{background:#f7f9fc;border-radius:8px;padding:7px}#live-week .pick-cover{color:#16833b;font-weight:800}#live-week .pick-behind{color:#c62828;font-weight:800}#live-week .pick-push{color:#111;font-weight:800}.stand-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:8px;margin:12px 0 20px}.stand-grid div{background:#f7f9fc;border:1px solid #e1e7f0;border-radius:10px;padding:10px;text-align:center}.season-divider{border:0;border-top:1px solid #dfe6ef;margin:22px 0}@media(max-width:650px){.stand-grid{grid-template-columns:repeat(2,1fr)}#live-week .picks-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  }
  function renderStandingsPage(data){const section=document.getElementById('standings');if(!section)return false;const w2=data.standings.map(s=>({...s,money:WEEK2_MONEY[s.name]||0}));section.innerHTML=`<div class="card"><h2>Standings</h2><h3>Week 2 final standings</h3><p class="muted">Final Week 2 record, points and money.</p>${cards(w2)}<hr class="season-divider"><h3>Season total</h3><p class="muted">Week 1 and Week 2 combined.</p>${cards(seasonRows(data))}</div>`;return true;}
  function render(data){const status=document.getElementById('live-week-status');if(status)status.textContent='Published Week '+data.week.week_number+' picks · scores refresh automatically about every minute.';const ls=document.getElementById('live-week-standings');if(ls)ls.innerHTML='<h3>Week '+esc(data.week.week_number)+' standings so far</h3>'+cards(data.standings);renderStandingsPage(data);const lg=document.getElementById('live-week-games');if(!lg)return;lg.innerHTML=[['college','COLLEGE FOOTBALL'],['nfl','NFL']].map(([sport,label])=>`<h3>${label}</h3>`+data.games.filter(g=>g.sport===sport).map(g=>{const cls=g.completed?'game-final':g.status==='in'?'game-live':'game-pre',score=(g.away_score!==null&&g.home_score!==null)?`${esc(g.away_team)} ${g.away_score} · ${esc(g.home_team)} ${g.home_score}`:`${esc(g.away_team)} @ ${esc(g.home_team)}`,ats=g.completed&&g.ats_winner?`ATS: ${esc(g.ats_winner==='Push'?'Push':g.ats_winner+' covered')}`:(g.status==='in'&&g.ats_winner?`Current cover: ${esc(g.ats_winner)}`:'');return `<div class="card ${cls}"><div><span class="live-badge">${esc(g.status_detail||(g.completed?'Final':'Scheduled'))}</span></div><div class="scoreline">${score}</div><div class="muted">Line: ${esc(g.favorite_team)} ${esc(g.spread)}${ats?' · '+ats:''}</div><div class="picks-grid">${data.participants.map(name=>{const p=pickFor(data,g.id,name),m=atsMargin(g,p),pc=pickClass(m);return `<div><b>${esc(name)}</b>: <span class="${pc}">${esc(p)}${fmtMargin(m)}${pickMark(g,p)}</span></div>`;}).join('')}</div></div>`;}).join('')).join('');}
  async function loadLiveWeek(){ensureUI();const status=document.getElementById('live-week-status');try{if(status)status.textContent='Refreshing Week 3…';const {data,error}=await sb.functions.invoke('pool-live',{body:{week_number:2}});if(error)throw error;if(data?.error)throw new Error(data.error);render(data);}catch(e){if(status)status.textContent='Unable to load Week 3 live view: '+(e?.message||'unknown error');}}
  window.loadLiveWeek=loadLiveWeek;
  function start(){ensureUI();document.addEventListener('click',e=>{const b=e.target.closest?.('#app nav button');if(b&&b.textContent.trim()==='Standings')setTimeout(loadLiveWeek,150);},true);setTimeout(loadLiveWeek,800);setInterval(()=>{const live=document.getElementById('live-week')?.classList.contains('show'),stand=document.getElementById('standings')?.classList.contains('show');if(live||stand)loadLiveWeek();},60000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();