import assert from 'node:assert/strict';
import {buildCandidates,fetchCandidates} from '../supabase/functions/college-admin/providers.mjs';
const now=Date.parse('2026-09-14T12:00:00Z');
const week={season:2026,picks_due_at:'2026-09-18T04:00:00Z'};
const teams=[{id:1,school:'Alpha',mascot:'Tigers',alternateNames:[]},{id:2,school:'Beta',mascot:'Bears',alternateNames:[]}];
const game={id:1,homeId:1,awayId:2,homeTeam:'Alpha',awayTeam:'Beta',startDate:'2026-09-19T23:30:00Z',startTimeTBD:false,completed:false};
const event={id:'odds1',home_team:'Alpha Tigers',away_team:'Beta Bears',commence_time:game.startDate,bookmakers:[{key:'draftkings',last_update:new Date(now).toISOString(),markets:[{key:'spreads',outcomes:[{name:'Alpha Tigers',point:-3.5},{name:'Beta Bears',point:3.5}]}]}]};
const build=(games=[game],events=[event],teamList=teams,previous=[])=>buildCandidates(games,teamList,events,week,previous,now);
const row=build()[0];assert.equal(row.favorite_team,'Alpha');assert.equal(row.spread,-3.5);assert.equal(row.issue,'');
assert.equal(build(Array.from({length:30},(_,i)=>({...game,id:i+1}))).length,30);
assert.equal(build([{...game,startDate:'2026-09-17T23:00:00Z'}]).length,0);
assert.equal(build([{...game,startTimeTBD:true}])[0].kickoff_at,null);
assert.equal(build([{...game,startTimeTBD:true}])[0].issue,'Kickoff time TBD');
assert.equal(build([game],[])[0].issue,'No matching odds event');
assert.equal(build([game],[event,event])[0].issue,'Ambiguous provider match');
assert.equal(build([game],[{...event,home_team:'Unknown'}])[0].favorite_team,null);
assert.equal(build([game],[{...event,commence_time:'2026-09-19T20:00:00Z'}])[0].issue,'Providers disagree on kickoff time');
assert.equal(build([],[],teams,[row])[0].issue,'No longer in the upcoming schedule');
const pickem=structuredClone(event);pickem.bookmakers[0].markets[0].outcomes.forEach(o=>o.point=0);
assert.match(build([game],[pickem])[0].issue,/Pick’em/);
const stale=structuredClone(event);stale.bookmakers[0].last_update='2026-09-01T00:00:00Z';assert.match(build([game],[stale])[0].issue,/stale/);
const duplicateTeams=[...teams,{id:3,school:'Alpha',mascot:'Tigers'}];assert.equal(build([game],[event],duplicateTeams)[0].favorite_team,null);
await assert.rejects(()=>fetchCandidates(week,[],()=>null),/setup needed/);
await assert.rejects(()=>fetchCandidates(week,[],()=> 'private-key',async()=>new Response('{}',{status:429})),/429/);
globalThis.Deno={env:{get:()=>undefined},serve:()=>{}};
const {handle}=await import('../supabase/functions/college-admin/index.ts');
const env=name=>({SUPABASE_URL:'https://example.test',SUPABASE_SERVICE_ROLE_KEY:'server-key'}[name]);
assert.equal((await handle(new Request('https://fn.test',{method:'POST'}),env)).status,401);
assert.equal((await handle(new Request('https://fn.test',{method:'GET'}),env)).status,405);
let calls=0;
const fetcher=async url=>{calls++;return Response.json(url.endsWith('/auth/v1/user')?{id:'player'}:[{admin_user_id:'admin'}]);};
assert.equal((await handle(new Request('https://fn.test',{method:'POST',headers:{Authorization:'Bearer user'},body:'{"action":"refresh"}'}),env,fetcher)).status,403);
assert.equal(calls,2,'Non-admin stops before provider or draft access');
console.log('PASS: provider matching, 30-game list, cutoff, TBD, ambiguous/stale/missing odds, pick’em, refresh retention, missing keys, provider errors and unauthenticated/non-admin access.');
