import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {buildMetadata,fetchMetadata} from '../supabase/functions/college-admin/metadata.mjs';
const {view,group}=createRequire(import.meta.url)('../college-view.js');
const teams=[{school:'Alpha',conference:'SEC',classification:'fbs'},{school:'Beta',conference:'Big Ten',classification:'fbs'},{school:'Gamma',conference:'Mountain West',classification:'fbs'},{school:'Notre Dame',conference:'ACC',classification:'fbs'},{school:'Small College',conference:'Division III',classification:'iii'}];
const polls=[{season:2026,seasonType:'regular',week:2,polls:[{poll:'AP Top 25',ranks:[{school:'Alpha',rank:5},{school:'Beta',rank:9}]}]},{season:2026,seasonType:'regular',week:9,polls:[{poll:'AP Top 25',ranks:[{school:'Alpha',rank:1}]}]}];
const ratings=[{year:2026,team:'Gamma',ranking:45},{year:2026,team:'Alpha',ranking:4},{year:2026,team:'Beta',ranking:12}];
const metadata=buildMetadata(teams,polls,ratings,2026,3);
assert.equal(metadata.ap_week,2);assert.equal(metadata.teams[0].ap,5);
assert.equal(metadata.teams[2].sp,45);
const base={kickoff_at:'2026-09-19T20:00:00Z',line_updated_at:new Date().toISOString(),favorite_team:'Alpha',spread:-3,issue:''};
const games=[{...base,id:'1',home_team:'Small College',away_team:'Unknown',spread:null,issue:'No odds'},{...base,id:'2',home_team:'Alpha',away_team:'Small College',spread:-10},{...base,id:'3',home_team:'Alpha',away_team:'Beta'},{...base,id:'4',home_team:'Gamma',away_team:'Notre Dame',spread:-1}];
const original=JSON.stringify(games),selected=new Set(['1','3']);
assert.deepEqual(view(games,metadata).map(r=>r.game.id),['3','2','4','1']);
assert.deepEqual(view(games,metadata,{conference:'SEC'}).map(r=>r.game.id),['3','2']);
assert.deepEqual(view(games,metadata,{conference:'Other FBS'}).map(r=>r.game.id),['4']);
assert.equal(group(metadata.teams[3]),'Independents');
assert.equal(view(games,metadata,{ranked:'both'}).length,1);
assert.equal(view(games,metadata,{ranked:'top50'}).length,3);
assert.equal(view(games,metadata,{verified:true}).length,3);
assert.equal(view(games,metadata,{search:'small college'}).length,2);
assert.equal(view(games,metadata,{conference:'SEC',search:'gamma'}).length,0);
assert.deepEqual(view(games,metadata,{sort:'spread'}).map(r=>r.game.id),['4','3','2','1']);
assert.equal(view(games,metadata,{selected:true},selected).length,2);
view(games,metadata,{conference:'SEC'},selected);assert.deepEqual([...selected],['1','3']);assert.equal(JSON.stringify(games),original);
assert.equal(view(games,{}).length,4,'Missing metadata must not hide games');
assert.equal(view(games,metadata,{conference:'All'}).length,4);
const stale={...games[2],line_updated_at:'2000-01-01T00:00:00Z'};assert.equal(view([stale],metadata,{verified:true}).length,0);
const unavailable=await fetchMetadata({season:2090,week_number:3},()=> 'key',async()=>new Response('',{status:403}));assert.equal(unavailable.teams.length,0);assert.equal(unavailable.warnings.length,3);
console.log('PASS: conference/Notre Dame/Other FBS, AP/SP+ Top 50, featured order, search combinations, spread sort, stale odds, missing metadata and hidden-selection preservation.');
